from pydantic import BaseModel, Field
from typing import List


class ATSAnalysis(BaseModel):
    """Deterministic ATS score breakdown for the resume."""

    score: int = Field(
        ...,
        ge=0,
        le=100,
        description="Final ATS score out of 100.",
    )

    keyword_score: int = Field(
        ...,
        ge=0,
        le=30,
        description="Keyword optimization score out of 30.",
    )

    structure_score: int = Field(
        ...,
        ge=0,
        le=20,
        description="Resume structure score out of 20.",
    )

    completeness_score: int = Field(
        ...,
        ge=0,
        le=20,
        description="Content completeness score out of 20.",
    )

    skills_score: int = Field(
        ...,
        ge=0,
        le=20,
        description="Skills relevance score out of 20.",
    )

    readability_score: int = Field(
        ...,
        ge=0,
        le=10,
        description="Formatting and readability score out of 10.",
    )

    issues: List[str] = Field(
        default_factory=list,
        description="List of ATS issues or improvement opportunities identified from the resume text.",
    )


class AIAtsInsights(BaseModel):
    """Qualitative ATS insights generated by Gemini for resume content review."""

    key_skills: List[str] = Field(
        default_factory=list,
        description="Important technical and professional skills explicitly supported by the resume text.",
    )

    strengths: List[str] = Field(
        default_factory=list,
        description="Qualitative ATS strengths relevant to hiring and resume scanning.",
    )

    weaknesses: List[str] = Field(
        default_factory=list,
        description="Qualitative ATS weaknesses or content gaps relevant to job application success.",
    )

    potential_issues: List[str] = Field(
        default_factory=list,
        description="Potential ATS or resume-content issues such as vague descriptions, weak sections, or missing evidence.",
    )

    recommendations: List[str] = Field(
        default_factory=list,
        description="Specific, actionable recommendations to improve the resume for ATS and hiring outcomes.",
    )


class CombinedAtsResult(BaseModel):
    """Combined deterministic ATS score and qualitative AI ATS insights."""

    ats: ATSAnalysis = Field(..., description="Deterministic ATS score, calculated from extracted resume text.")
    ai_insights: AIAtsInsights = Field(..., description="Qualitative ATS recommendations and issues from Gemini.")


class ResumeAnalysis(BaseModel):
    """Structured resume analysis returned by the AI Resume Analyzer.

    All fields are required and validated as specified below.
    """

    professional_summary: str = Field(
        ...,
        description=(
            "Concise summary of the candidate derived only from resume content. "
            "Should be 1-3 sentences describing background, experience, education, and main domains of expertise when available."
        ),
    )

    strengths: List[str] = Field(
        ...,
        description=(
            "List of the candidate's verifiable strengths as separate items. "
            "Each item must be supported by the resume content (skills, projects, achievements, roles)."
        ),
    )

    weaknesses: List[str] = Field(
        ...,
        description=(
            "List of areas for improvement based on the resume. "
            "Do not invent weaknesses; only include items supported by the resume."
        ),
    )

    skills: List[str] = Field(
        ...,
        description=(
            "List of skills explicitly present in the resume (technical and professional). "
            "Do not add skills that do not appear in the resume."
        ),
    )

    recommendations: List[str] = Field(
        ...,
        description=(
            "Actionable, specific recommendations to improve the resume. "
            "Recommendations should be tied to observed weaknesses and be implementable."
        ),
    )

    ats: ATSAnalysis = Field(
        default_factory=lambda: ATSAnalysis(
            score=0,
            keyword_score=0,
            structure_score=0,
            completeness_score=0,
            skills_score=0,
            readability_score=0,
            issues=[],
        ),
        description="Deterministic ATS scoring breakdown for the resume.",
    )


class ResumeOptimizationSection(BaseModel):
    """A single section of resume optimization with original and improved content."""

    original: str = Field(..., description="The original resume content for this section.")
    optimized: str = Field(..., description="An improved version of the same section using only the original facts.")
    notes: List[str] = Field(
        default_factory=list,
        description="Short notes describing the wording, action-verb, and ATS improvements applied.",
    )


class BeforeAfterComparisonItem(BaseModel):
    """Structured original-vs-optimized comparison for a specific resume section or item."""

    section: str = Field(..., description="The resume section or item being compared, such as professional_summary or experience.")
    original_text: str = Field(default="", description="The original resume content before optimization.")
    optimized_text: str = Field(default="", description="The optimized version of the same content after processing.")
    reason_for_change: str = Field(
        default="",
        description="A plain-language explanation for why the wording was improved without fabricating facts.",
    )


class ResumeOptimization(BaseModel):
    """Structured resume optimization output from Gemini.

    The ATS score remains authoritative and is not generated here.
    """

    professional_summary: ResumeOptimizationSection = Field(
        ...,
        description="Original and improved professional summary, preserving facts while improving clarity.",
    )
    experience: ResumeOptimizationSection = Field(
        ...,
        description="Original and improved experience description, preserving the same responsibilities and achievements.",
    )
    skills: ResumeOptimizationSection = Field(
        ...,
        description="Original and improved skills wording, standardized without inventing new technologies.",
    )
    bullet_points: ResumeOptimizationSection = Field(
        ...,
        description="Original and improved bullet-point content, making wording more concise and achievement oriented.",
    )
    optimization_notes: List[str] = Field(
        default_factory=list,
        description="High-level notes describing how the resume was improved without fabricating information.",
    )
    before_after_comparison: List[BeforeAfterComparisonItem] = Field(
        default_factory=list,
        description="Structured before/after evidence showing the original content and the optimized content side by side.",
    )
    target_role: str = Field(
        default="",
        description="Target role or job title the optimization was tailored to, when a specific job description is provided.",
    )
    job_description: str = Field(
        default="",
        description="The target job description used to tailor the optimization, when available.",
    )
    job_specific: bool = Field(
        default=False,
        description="Whether the optimization was tailored to a specific job description.",
    )
    ats_score_remains_authoritative: bool = Field(
        default=True,
        description="The deterministic ATS score remains the system-authoritative source of truth.",
    )


class DownloadOptimizedResumeRequest(BaseModel):
    """Structured request for exporting the already-generated optimized resume data."""

    filename: str = Field(default="resume.pdf", description="Original resume filename used as a hint for the exported download name.")
    target_role: str = Field(default="", description="Optional target role used for job-specific optimization exports.")
    optimization: ResumeOptimization = Field(..., description="The optimized resume content to export.")


class JobSpecificAnalysis(BaseModel):
    """Structured job-targeted resume analysis generated from resume + job description."""

    job_title: str = Field(..., description="The job title or role inferred from the job description.")
    matching_skills: List[str] = Field(
        default_factory=list,
        description="Skills present in the resume that align with the job description.",
    )
    matching_keywords: List[str] = Field(
        default_factory=list,
        description="Important job keywords or phrases explicitly represented in the resume.",
    )
    missing_or_weak_requirements: List[str] = Field(
        default_factory=list,
        description="Requirements from the job description that are absent, weakly represented, or not clearly demonstrated in the resume.",
    )
    missing_requirements: List[str] = Field(
        default_factory=list,
        description="Important job requirements that are absent or not demonstrated in the resume.",
    )
    missing_keywords: List[str] = Field(
        default_factory=list,
        description="Important job-description keywords or phrases that are not adequately represented in the resume.",
    )
    missing_skills: List[str] = Field(
        default_factory=list,
        description="Skills or capabilities required by the job that are not demonstrated by the resume.",
    )
    keyword_alignment: List[str] = Field(
        default_factory=list,
        description="Important job keywords or phrases and whether they appear in the resume.",
    )
    relevant_experience: List[str] = Field(
        default_factory=list,
        description="Resume experience areas directly relevant to the target job requirements.",
    )
    experience_alignment: str = Field(
        ...,
        description="Summary of how the candidate's existing experience aligns with the role's responsibilities and requirements.",
    )
    resume_strengths: List[str] = Field(
        default_factory=list,
        description="Resume strengths that are particularly relevant to the target job.",
    )
    improvement_suggestions: List[str] = Field(
        default_factory=list,
        description="Actionable suggestions for improving the resume for this specific role, based only on facts present in the resume.",
    )
    overall_fit: str = Field(
        ...,
        description="Overall assessment of job fit based only on the resume and the job description.",
    )
    score_explanation: str = Field(
        default="",
        description="Plain-language explanation of why the job match score was assigned.",
    )
    job_match_score: int = Field(
        default=0,
        ge=0,
        le=100,
        description="Numeric job match score between 0 and 100, computed from matching evidence and missing requirements.",
    )
    ats_score_remains_authoritative: bool = Field(
        default=True,
        description="The deterministic ATS score remains the authoritative ATS score and is not replaced by this AI analysis.",
    )
